# Generated by Django 4.2.18 on 2025-01-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AllFieldTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integer_field", models.IntegerField(default=0)),
                ("positive_integer", models.PositiveIntegerField(default=0)),
                ("small_integer", models.SmallIntegerField(default=0)),
                ("big_integer", models.BigIntegerField(default=0)),
                ("decimal_field", models.DecimalField(decimal_places=2, max_digits=10)),
                ("float_field", models.FloatField(default=0.0)),
            ],
        ),
    ]
